### ISSUE TITLE
Typos and missing commas

### ISSUE THREAD

**Issue by carmacleod** [w3c/personalization-semantics#1]
- However what is familiar for one user may be new for another requiring them to learn new symbols. 
  --> needs a couple of commas:
  However, what is familiar for one user may be new for another, requiring them to learn new symbols. 
  (note that this sentence occurs twice in the document)
- programanticaly --> programmatically 
- At at the user end --> At the user end
- keyboard short cut  --> keyboard shortcut 
- In addition it could be identified as important 
  --> needs a comma:
  In addition, it could be identified as important 
  (note that this sentence occurs twice in the document)
- non vocal --> non-vocal
  (there are 2 instances of non vocal in the document)
- These symbols are in fact peoples language.
  --> needs an apostrophe after peoples:
  These symbols are in fact peoples' language.
  (this sentence appears twice in the document)
- Unfortunately many of these symbols are both subject to copy write and are not interoperable. 
  --> needs a comma, and change copy write to copyright:
  Unfortunately, many of these symbols are both subject to copyright and are not interoperable. 
- mens clothing --> men's clothing
- more frequently use womens clothing option
  --> more frequently used women's clothing option
- (see bellow).  --> (see below). 
- Example user experience:,  --> Example user experience:    (i.e. remove the extra comma)
- compose(default importance = "critical") --> add a space after compose
- Proposed attribute:coga-destination  --> add a space after the colon
  (also, add space after colon for attribute:coga-context  and  attribute:coga-numberfree)
- diffrent  --> different 
- contactus --> contact us
- gender#femail  -->  gender#female
- not only thoughs who can implement RDF logic
  -->  not only those who can implement RDF logic
- Further ,   --> remove the extra space before the comma
- for Non verbal people
  --> **nonverbal** is all one word, and it does not need to be capitalized in the middle of the sentence
- alternatively wordnet nodes could be referenced. 
  --> Alternatively, wordnet nodes could be referenced. 
- High important  --> Highly important
- for people learn via keypoints or examples
  --> for people **to** learn via **key points** or examples
- value :    --> remove the extra space before the colon
- information.or  --> information or 
- tool tip  --> tooltip
- inforamtion  -->  information
- additonal  -->  additional 
- values:tooltips  -->  values: tooltips    (i.e. add space after colon)
- alternitive  -->  alternative 
- it's direct parent  -->  its direct parent    (don't need apostrophe unless short for "it is")
- mid sentence  -->  mid-sentence
- claiming there preferred  -->  claiming they preferred
- privacy ,it    -->  privacy, it     (i.e. move comma before space)
- experience different amount of   -->  experience different amounts of 
- turn off distractions such as skype, and facebook, across different devices, 
  -->  turn off distractions, such as Skype and Facebook, across different devices, 
- one miunet  -->  one minute
- If multiple names are used they can be separated by a coma.
  -->  If multiple names are used**,** they can be separated by a **comma**.
- locaction  --> location 
- makes this message relevent  --> makes this message **relevant**
- "home" nd "work"  -->  "home" and "work"
- If multiple locations are relivent they can be separated by a coma.
  -->  If multiple locations are **relevant** they can be separated by a **comma**.
- "my calender"   --> "my calendar" 
- lable   -->  label

**Comment by lseeman** [comment]
Thank you! would you like to join the task force?

**Comment by carmacleod** [comment]
Thanks for the offer, @lseeman, but I'm afraid I wouldn't be able to give it enough time.

**Comment by becka11y** [comment]
Fixed the ones still present in the document in August, 2018

**Comment by clapierre** [comment]
All issues addressed in #86
