### ISSUE TITLE
Content Module - supported values are inconsistent 

### ISSUE THREAD

**Issue by snidersd** [w3c/personalization-semantics#109]
[Content Module 1.0 ](https://w3c.github.io/personalization-semantics/content/index.html)-> 3.5.1 -> Supported values 
This is the only section that has "Supported Values" and it’s not clear what the difference is between the supported values listed in 3.5.1 which are inconsistent with the values listed in 3.5.4. 
Should supported values in 3.5.1 be the same as the values listed in 3.5.4 or be removed?

**Comment by snidersd** [comment]
@clapierre Should I update Distractions 3.5.1 - Supported values: messages, offer, overlay, sensory.
or remove the Supported values from this section since they are covered in 3.5.4?

**Comment by clapierre** [comment]
@snidersd sounds like  we already addressed this one by adding a values section to each of the other   areas (purpose, simplification and distraction so I think we can close this out right.

**Comment by snidersd** [comment]
@clapierre The issue is that the supported values still exist in 3.5.1 and they do not match the values that are in the new section 3.5.4. IMO the supported values listed (that are also inaccurate) in 3.5.1 still need to be removed before this is closed.

**Comment by clapierre** [comment]
You are correct, the issue here is that 3.5.1 and the examples in 3.5.2 don't match the new values we changed in 3.5.4.  So we just need to fix those to align with 3.5.4.  I will work on this when I get a chance.  Thanks @snidersd

**Comment by clapierre** [comment]
I looked at the other sections and you are right this 3.5.1 was the only Description section which included the accepted values, so I removed them from this section.  We just need to have GitHub.io update which Roy is looking into.  This issue I believe once this goes live is then correct and we can close this issue.

**Comment by ruoxiran** [comment]
> I looked at the other sections and you are right this 3.5.1 was the only Description section which included the accepted values, so I removed them from this section. We just need to have GitHub.io update which Roy is looking into. This issue I believe once this goes live is then correct and we can close this issue.

thanks all, I will close this issue.
