### ISSUE TITLE
License on explainer

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/personalization-semantics#113]
My understanding from [the charter](https://www.w3.org/2018/08/apa-charter#normative) is that the [Personalization Semantics explainer](https://w3c.github.io/personalization-semantics/) is not normative; as a result, it should use the [Document and Software License](https://www.w3.org/2018/08/apa-charter#licensing)

**Comment by clapierre** [comment]
Thanks Dom, will update this.

**Comment by snidersd** [comment]
@clapierre This issue is complete. Can it be closed?
