### ISSUE TITLE
Typo - filed vs field

### ISSUE THREAD

**Issue by thaddeus-cambron** [w3c/personalization-semantics#117]
Personalization Semantics Content Module 1.0

Section 3.1 should read field vs. filed 

https://raw.githack.com/w3c/personalization-semantics/rewrite-prototype/content/index.html#attributes-related-with-token

**Comment by thaddeus-cambron** [comment]
Created PR #118

**Comment by thaddeus-cambron** [comment]
Also misspelled in 3.1.1

**Comment by clapierre** [comment]
This issue has been resolved
