### ISSUE TITLE
TAG Explainer

### ISSUE THREAD

**Issue by clapierre** [w3c/personalization-semantics#132]
Here are this items TAG requests we have in our explainer.  I removed those which we already have.

**Participate**
[Issue tracker]
[Discussion forum]

**Goals [or Motivating Use Cases, or Scenarios]**
[What is the end-user need which this project aims to address?]
 
_I think we covered this with 1.1 and 1.2 right?_

**Non-goals**
[If there are "adjacent" goals which may appear to be in scope but aren't, enumerate them here. This section may be fleshed out as your design progresses and you encounter necessary technical and other trade-offs.]

_Do we have any?_

**[API x]**

[For each related element of the proposed solution - be it an additional JS method, a new object, a new element, a new concept etc., create a section which briefly describes it.]

**Key scenarios**

[If there are a suite of interacting APIs, show how they work together to solve the key scenarios described.]

Scenario x

[Description of the end-user scenario]

// Sample code demonstrating how to use these APIs to address that scenario.

**Detailed design discussion**

[Tricky design choice - X]

[Talk through the tradeoffs in coming to the specific design point you want to make.]

**Considered alternatives**

[This should include as many alternatives as you can, from high level architectural decisions down to alternative naming choices.]

[Alternative 1]

[Describe an alternative which was considered, and why you decided against it.]

**Stakeholder Feedback / Opposition**

[Implementors and other stakeholders may already have publicly stated positions on this work. If you can, list them here with links to evidence as appropriate.]

[Implementor A] : Positive
[Stakeholder B] : No signals
[Implementor C] : Negative
[If appropriate, explain the reasons given by other implementors for their concerns.]

**Comment by lseeman** [comment]
opened at https://github.com/w3ctag/design-reviews/issues/476
