### ISSUE TITLE
Can we refer to HTML autocomplete values by reference?

### ISSUE THREAD

**Issue by becka11y** [w3c/personalization-semantics#138]
This comes from a response from I18N to our answer to one of their questions in the review:
Question: If the spec (or its implementation) deals with names, addresses, time & date formats, etc

Our response: The data-purpose attribute does pattern after autocomplete attribute of HTML5 and author is responsible for any internationalization concerns.

I18N response: This section contains many potential issues for I18N, but these are mainly external to your spec (as you call out). Is there a way for you to not need to duplicate that spec's keywords, etc. and just import the fields by reference? You'll have to avoid breakage as we work with them or as their spec evolved :-).

I am opening this as a new issue to get ideas from the larger group.

**Comment by becka11y** [comment]
Without completely understanding the I18N issues with the proposed values it is a bit hard to make a recommendation. 

Perhaps we can make a numeric mapping table similar to what we do for symbol sets?  If we believe that the definitions of the names, addresses, and time formats will not change, we can assign a numeric value to each definition. That does make it more confusing for the author since they have to perform a translation but this can be accommodated for with editor macros and tooling.

But, if we expect the definitions to change rather than just the keywords, this strategy will not help.

**Comment by lseeman** [comment]
we think this is disscussed and handeled as much as we can.
