### ISSUE TITLE
Should grammar of symbology be defined?

### ISSUE THREAD

**Issue by aphillips** [w3c/personalization-semantics#141]
(From your I18N self-review #133)

> >  We are using numerical tokens which can be mapped to symbols sets, so we don't think this is an issue but request you look at this closer. Also the symbol sets themselves may be localized.

> Replacing a word with a number (which is used to obtain the symbol) initially seems okay. There are two things that immediately spring to mind to think about, though. First, the use of numbers is extended in one example to spell the phrase "cup of tea" (with each word taking one symbol). This depends strongly on the grammar of the language being recoded into symbols; I would have expected the symbols to have their own (somewhat language neutral) grammar.

**Comment by lseeman** [comment]
We believe these are addressed in #144 , but here are the main points for quick reference. 
Our use-cases is to map between different symbol sets in the same natural language. We are not enabling translation for different symbol sets across different natural languages at this time.

Also the reference numbers are from Bliss symbolics, which was designed to be an international language similar to Esperanto. Bliss have a published set of usage rules at: http://www.blissymbolics.org/images/bliss-rules.pdf. 

Please let us know if you have more questions.
