### ISSUE TITLE
Define how "sections of text" are selected or created

### ISSUE THREAD

**Issue by aphillips** [w3c/personalization-semantics#142]
(from your I18N self-review #133)

>>  Simplification allows for replacing sections of text with an alternative text, which the author will provide.

> It doesn't appear that this spec defines how "sections of text" are selected or created. Our concerns here generally have to do with how text is broken into subcomponents (such as words).

@becka11y suggests:

> We should have been more specific in our answer. The Simplification specification provides specific attribute values that specify the level of simplification needed. The assistive technology is responsible for providing the necessary modifications to meet the user’s needs. The original content author just identifies the sections that may need simplifying. Future specifications may require author provided alternative text and we will address this issue further.

This seems to address my concern in the short term. The longer term needs will depend on the features you provide and we can discuss as issues arise there. The main thing to keep your eye on will be processing that requires the user-agent to perform text segmentation or natural language understanding (I presume that the assistive technology probably has this already?)

**Comment by lseeman** [comment]
Thank you
With your permission we will be in-touch if we need user agents to perform text segmentation in future modules.

**Comment by snidersd** [comment]
Closing issue since we have not been advised of any objections.
