### ISSUE TITLE
Language or cultural relevance of specific symbol sets

### ISSUE THREAD

**Issue by aphillips** [w3c/personalization-semantics#146]
(From your I18N self-review #133)

>>>  If the spec (or its implementation) makes any reference to or relies on any cultural norms
>>   there are internationalized AAC symbol sets to address that concern. and we are supporting those translations
> Can you expand on this? I'm not sure I understand the relationship here. Are you saying this spec only covers a specific language or region AAC symbol set?

@becka11y suggested:

> To be more specific, the spec itself does not make any reference to or rely upon any cultural norms. The assistive technologies are responsible for the culturally appropriate personalization/simplification.

So your specification only provides the mechanism for attaching a given assistive technology to some text, but doesn't define anything about how it works nor make any language or culturally specific assumptions? If so, that should be sufficient to address any concerns.

**Comment by lseeman** [comment]
Thank you. If there are no more questions, we may close this issue.

NOTE: the reference numbers are from bliss symbolics, which was designed to be an international language similar to Esperanto.  You may be interested in the rules at http://www.blissymbolics.org/images/bliss-rules.pdf
