### ISSUE TITLE
Bidi considerations [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/personalization-semantics#155]
Action | Action>Values
https://www.w3.org/TR/personalization-semantics-content-1.0/#action-explanation
https://www.w3.org/TR/personalization-semantics-content-1.0/#values

> left | Changes the location of the selected item(s) to the left.

In the `values` section of `action`, there are a values that move positions `left` and `right`, but no corresponding logical values `start` and `end` that take into account bidirectional text handling (and the corresponding mirroring of layout). While there is a need for absolute left/right positioning, there should be a way to do logical positioning based on layout.

I also notice that there are no `up` or `down` values. Is this an omission? (The corresponding logical directions, using CSS's terminology, would be `block-start` and `block-end`)

For some illustrations that show what the impact of bidi is on page layout, see [this article](https://www.w3.org/International/questions/qa-html-dir#documentlevel).

**Comment by ruoxiran** [comment]
Becky has added start/end, up/down, updated defintion of left/right to refer people to next/previous if the navigation is logical rather than physical. Please find changes in pull request #163. Thank you for your comments.

**Comment by snidersd** [comment]
Changes complete in the latest draft.
