### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jducrot** [w3c/personalization-semantics#159]
Friendly heads up, noticed a few typos while reading through the doc:

- 1.1: Includudes -> Includes
- 1.9: nessessary -> necessary, afforardance -> affordance
- 1.10: contats -> contacts
- 3.5.5.1: anther  -> another
- 4.1.1: used less "then" -> than
- 4.1.4: non-verbal -> nonverbal

PS: The presentation Roy Ran did as part of WAI interactive update on July 23 2020 peaked my interest on this topic and I'd love to contribute even in small ways like spell checking.

**Comment by clapierre** [comment]
@jducrot what document are you referring to?

**Comment by clapierre** [comment]
I found the document, it was the Requirements Document.
