### ISSUE TITLE
Content Module 1: destination vs. rel attribute

### ISSUE THREAD

**Issue by dauwhe** [w3c/personalization-semantics#172]
There seems to be some overlap between the `destination` attribute and the existing `rel` attribute. What would be the difference between `data-destination="help"` and `rel="help"`? Would authors be encouraged to use both?

**Comment by johnfoliot** [comment]
Thank you for your question/feedback.

The difference between the `@rel` attribute values and `@destination` attribute values only has one apparent overlap: Help. 

Our use cases currently see applying the value of **_help_** to both the `@destination` AND `@action` attributes (different outcomes), and we do not believe that having this value will introduce any conflicts or collisions with `@rel` usage. Conversely, removing the help value from `@destination` would leave the appearance of a hole in our specification. 

Additionally, we envision feature-specific helper-applications that individual users would deploy to take advantage of this additional semantic markup, and we believe sticking with a common authoring pattern would be beneficial to those anticipated tools (i.e. support ALL of our spec, and not need to research other specs to deliver the required functionality). This would not be the first time that a content author can construct the same semantic outcome using more than one technique, although specific to our use cases we would (of course) recommend the `@destination="help"` author pattern to address the user need.
