### ISSUE TITLE
coga glossary

### ISSUE THREAD

**Issue by lseeman** [w3c/personalization-semantics#173]
we have an editors note that
We intend to incorporate additional terms from the glossary from the Cognitive and Learning Disabilities Accessibility Task Force, when it is ready. If there are non-editorial differences, we will use the term definitions above. See the COGA Glossary.

Note that the coga glossary is published for V1. We should incoperate as needed. See https://w3c.github.io/coga/content-usable/#glossary

we should also review any other editors notes

**Comment by lwolberg** [comment]
A pointer to the glossary is included in Module 1.0
