### ISSUE TITLE
Does/should flagging any @distraction value imply @simplification=low?

### ISSUE THREAD

**Issue by matatk** [w3c/personalization-semantics#182]
Module 1 states that [`distraction` "is intended" to be applied to things that are not essential](https://w3c.github.io/personalization-semantics/content/#description-3).

Is the intent that anything flagged as a distraction would be assumed to be of "low" `simplification` essentiality? Would making such a link break any known, or preclude any foreseen, cases? Would it cause author confusion?

If we mean "is intended to be used" in the "should" RFC/ARIA sense, then the `simplification` part is technically optional, so we should clarify that it's expected, but not mandatory.

If we're sure that anything flagged as a `distraction` is _not_ essential, then the `simplification=low` part could be implicit. However, there is a "should" clause in the spec about providing an accessible name for the distracting content and I'm not sure why (so am quite possibly missing something). Perhaps the name could be used to offer the user the option of reviewing which content was hidden on the grounds of it being distracting, so at least they could find out that they're missing something? (I've just realised that could be the reason and it sounds like a neat feature :-).)

**Comment by matatk** [comment]
I believe we agreed right at the end of https://www.w3.org/2021/05/24-personalization-minutes.html that we should leave this as-is, because whilst a distraction (probably?) can't be `critical` it _could_ be `moderate` or `low`.

**Comment by matatk** [comment]
Just a quick note that the discussion seems to start at https://www.w3.org/2021/05/24-personalization-minutes.html#x170

**Comment by snidersd** [comment]
Closing this issue after confirming that there were no objections to leaving distraction as-is in the [24 May meeting minutes](https://www.w3.org/2021/05/24-personalization-minutes.html#x170).
