### ISSUE TITLE
Implied essentiality levels of some @action values

### ISSUE THREAD

**Issue by matatk** [w3c/personalization-semantics#184]
I had some questions about the implied level of essentiality of some of the [`action` attribute values](https://w3c.github.io/personalization-semantics/content/#values):

* `delete` isn't implicitly critical (but I expected it to be); do we know why? I know there is a [note in the spec about the "delete" function being not necessarily essential for some tasks](https://w3c.github.io/personalization-semantics/content/#values-2), so maybe that's why, but it seems quite context-dependant.
* `escape` feels like it should be implicitly critical too, but isn't; do we know why?
   - I note we have a `cancel` action too, which _is_ marked as critical; `cancel` is specified as relating entirely to dialogs. I wonder if it's a subset of `escape`?

This maybe relates to (but is a separate/more specific question than) #66

**Comment by lseeman** [comment]
charles is adding to escape fro clarification . see mintes for 24/5/2001
other issues are agreeed

**Comment by clapierre** [comment]
Currently we have the following in our list of values in section 3.1.4 of the Content Module 1

cancel | Closes the dialog and discards any changes the user may have made within that dialog. (Implied simplification = "critical".)
-- | --

escape | Typically used to abort, cancel or change what is currently being displayed on the screen. A common application of the the esc key is to leave full screen mode.
-- | --

I propose the following for both cancel and escape

cancel | Closes the dialog and discards any changes the user may have made within that dialog. (Implied simplification = "critical", the reason being if there is no `escape` option `cancel` must be present to abort the operation)
-- | --

escape | Typically used to abort, cancel or change what is currently being displayed on the screen. A common application of the the esc key is to leave full screen mode. (implied simplification = "critical", the reason being if there is no `cancel` option `escape` must be present to abort the operation)
-- | --

I am fine if we don't feel we also need to justify `cancel` as requiring critical simplification and leave its definition alone and only update `escape`.

**Comment by matatk** [comment]
Just a quick note that we also discussed this on the group call: https://www.w3.org/2021/05/24-personalization-minutes.html

**Comment by matatk** [comment]
Just a further note that the discussion in the minutes seems to start at https://www.w3.org/2021/05/24-personalization-minutes.html#x103

**Comment by johnfoliot** [comment]
Close per Issue #194
