### ISSUE TITLE
coga-gap-analysis: keygen has been removed

### ISSUE THREAD

**Issue by plehegar** [w3c/personalization-semantics#20]
In 2.3.2.2 Solutions for security and privacy, keygen is listed as a solution.

However, the latest version of HTML indicates:
[[
keygen has been removed 
]]
http://www.w3.org/TR/html52/changes.html#changes-fpwd

**Comment by ruoxiran** [comment]
Migrated to coga repository, please find this issue in https://github.com/w3c/coga/issues/67
