### ISSUE TITLE
aria-function is not defined yet used in example

### ISSUE THREAD

**Issue by jnurthen** [w3c/personalization-semantics#33]
The example at https://w3c.github.io/personalization-semantics/content/index.html#simplification-example includes aria-function. This needs removing or changing to whatever the current attribute is 

```html
<input aui-simplification="critical" aria-function="submit" value="Submit" type="submit"/>
```

**Comment by lseeman** [comment]
Thanks James!

**Comment by clapierre** [comment]
ADD EDNOTE

**Comment by lseeman** [comment]
this is aui-action. it had a (few)name changes. need to change it in the draft

**Comment by thaddeus-cambron** [comment]
I don't see this error in personalization-semantics/content/simplication.html. Was this resolved or does it live in another file?

**Comment by lseeman** [comment]
Hi James. We have changed the specification. See https://raw.githack.com/w3c/personalization-semantics/master/explainer.html#vocabulary-implementations

IE: 
We are using  data- attributes [html5]. Attributes in this form can be used in valid HTML to implement features recognized by browser extensions or other special processors. Personalization Semantics is using this approach to gain early implementation experience of the features in a way that is simple and likely to be accepted within the web ecosystem as an interim approach.

**Comment by jnurthen** [comment]
Looks good. Happy to close.
