### ISSUE TITLE
is symbol correct

### ISSUE THREAD

**Issue by lseeman** [w3c/personalization-semantics#36]
the personlization specification 
https://w3c.github.io/personalization-semantics/content/index.html#use_case_interoperable_symbols
and
https://w3c.github.io/personalization-semantics/content/index.html#symbol-explanation
Should be check for accuracy 

Is word net the best option? should we recomend something else?

Check with EA and m.lundalv and Chochai
----
also potential better wording:

We would like to create interoperable symbol sets for those with complex communication needs using Alternative and Augmentative Communication (AAC) systems. AAC systems designed for people who are non-verbal often use symbols with or without text.  End-users tend to only learn one symbol set and cannot easily communicate with other symbol users in a written format or may struggle to understand different symbols used in different applications. Some symbols are subject to copyright and cannot be shared across applications.  However, there are open symbol sets that can be shared and mapped against concepts, generating representative text.  This text can be translated into different languages and even used to present a different set of symbols. If users' symbols are mapped to the same concepts then user agents can load the user understandable symbols and enable access to the web and other applications. 
*User experience:* AAC users, those working with AAC users and others will be able to load symbols that they understand into different applications that have been made by a different provide

**Comment by clapierre** [comment]
Updated in latest pull request from myself

**Comment by lseeman** [comment]
We have sent this out to many groups and people working on the topic, so hopefuly it is OK....
