### ISSUE TITLE
3.6 aui-symbol makes no sense

### ISSUE THREAD

**Issue by johnfoliot** [w3c/personalization-semantics#47]
As currently written today, I cannot figure out what is being asked for here from content contributors.

     > symbol identifies the concept for symbols.

Huh? A symbol is a symbol? What does that mean?

     > symbol accepts the values of a URI or shortened URI.

But, what does that URI resolve to? The symbol? An explanation of the symbol? Something else?
Why is the content author linking to an external resource, and what is that resource supposed to be?

     > Note that namespaces are the only additional parsing that maybe required to identify the concept.

Namespaces??? How? Where? This makes no sense at all...

     > To help this be interoperable without an RDF parser we recommend referencing the most commonly used ontologies and the highest level concept.

Ontologies? This term is used exactly once in this specification, with no other explanation or reference. What does an ontology have to do with symbols?

RDF parser? What RDF parser? Where, how?

Currently, this section of the spec makes no sense, and is extremely unclear what is being asked of from the author. There is no clear goal, nor explanation of what the final outcome should look like, or achieve.

**Comment by lseeman** [comment]
Thank you so much for your comment. We think the new draft has addressed it . See https://www.w3.org/TR/personalization-semantics-content-1.0/ . Please open a new issue if there is still a problem.
