### ISSUE TITLE
prefix should not be used in vocabulary, only in implementations

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/personalization-semantics#48]
Since Personalization Semantics now defines an abstract vocabulary, there is no need to distinguish tokens from those of other metadata languages via a prefix. I think it is confusing to have the prefix baked into the vocabulary terms, and reduces future flexibility. So for example, I think the "aui-action" term should be just "action", etc.

In *vocabulary implementations* we would suggest the prefix in ways suitable to the implementation language:

* The ARIA section could say "prepend 'aui-' to the vocabulary term to get the role token, so 'action' becomes 'aui-action'." 
* The RDFa section would use a namespace instead, so could say "map the namespace prefix 'aui' to the namespace '@@' and use that with terms, so the 'action' property would become 'aui:action'." 
* The HTML Microdata section wouldn't use the prefix, but would say to use the "itemtype" attribute and use the same value as we define for the RDFa namespace.

**Comment by johnfoliot** [comment]
+1

Additionally, I wonder aloud if we could not reduce this all to one single attribute as well. Currently, ARIA supports the concept of "role"; could not all of this effort support a new concept of "purpose"? (A potential alternative would be "context"...)

For example, you could have any of the following:

ACTIONS:
- purpose="undo"   or (context="undo"?)
- purpose="reset"
- purpose="upload (download)"
- purpose="increase (decrease)"

DESTINATIONS:
- purpose="sitemap"   or (context="sitemap"?)
- purpose="products (services)"
- purpose="signin (signout)"
- purpose="post"

INPUT FIELDS*:
- purpose="name"
- purpose="cc-number"
- purpose="email"
- purpose="tel"
(Duplication of @autocomplete values. Is this necessary? For machines and machine-learning, all that is required is a consistent _@attribute="[fixed term]"_ that can be acted upon. Do we really need duplicates, especially with WCAG 2.1/SC 1.3.4?)

SIMPLIFICATION / DISTRACTION:
- purpose="critical"
- purpose="medium"
- purpose="low"

SYMBOLS:
(The current specification is extremely unclear how or why this is here. None-the-less, with a fixed collection of attribute values, they could all be mapped to potential symbol-sets; those symbols could then be triggered by the presence of the @purpose attribute+value across all sites via a 3rd-party setting or tool)

**Comment by michael-n-cooper** [comment]
The suggestion of using a "purpose" attribute is a tangent to this issue, so should be filed as a separate issue.
