### ISSUE TITLE
Missing attribute: @context

### ISSUE THREAD

**Issue by johnfoliot** [w3c/personalization-semantics#49]
The current draft includes two links to a proposed attribute: @context. However, while there are 2 links in the draft spec, there is no @context attribute defined anywhere in the document.

**Comment by clapierre** [comment]
Can you indicate where you found that Context Issue please.

**Comment by michael-n-cooper** [comment]
Doing a "find all" I find references to the context property in the Content module simplification property, and the Content module Use Cases. It is a property that was defined in an earlier draft of personalization semantics but isn't in the current one.

**Comment by lseeman** [comment]
John I think this is no longer relivent. let us know if it is still a problem
