### ISSUE TITLE
Clarity needed for actions vs destinations

### ISSUE THREAD

**Issue by joanmarie** [w3c/personalization-semantics#66]
Are these really destinations (e.g. and not actions)?
* `comment` - "submit a comment on the current item" (Submitting a comment seems like an action.)
* `left` - "Changes the location of the selected item(s) to the left." (Moving items seems like an action.)
* `right` - "Changes the location of the selected item(s) to the right." (Same observations as with `left`.)
* `post` - "post current item. Item will be visible to other parties." (Posting an item seems like an action. Also what is the difference between `post` and `comment`?)
* `related` - "Adds a related item(s) to a pre-selected list of items." (Again, seems like an action to me. Also what does "related" mean exactly? In the UIs I've seen, there are options to add the currently selected item(s) to a list. I've never seen an option to add "related" but not explicitly selected/obvious items to a list.)

Are these really actions (e.g. and not destinations)?
* `toc` - "opens a table of content" (If "opens" means "takes you to a table of contents page" then I don't see how that is any different in nature than `about`, which is a destination presumably taking one to a page with "about us" information.)
* `profile` - "opens the user's profile page" (Similar observation to `toc`. Being brought to another page of static content seems like a destination.)

These items seem similar in nature but some are actions and some are destinations and some are both. If their current categorization is correct, I believe some clarification is called for:
* Related to help:
  * Action: `help` - "opens a help function."
  * Destination: `help` - "a help function, support or instructions"
* Related to options:
  * Action: `settings` - "open settings and options"
  * Destination: `language` -  "language options"
* Related to moving items:
  * Action: `left` - "moves a selected item to the left to another column or list"
  * Destination: `left` - "Changes the location of the selected item(s) to the left."
  * Action: `right` - "moves a selected item to the right to another column or list"
  * Destination: `right` - "Changes the location of the selected item(s) to the right."

These items seem like they need some additional clarification:
* `signin` - "sign in to current web site or application" (If it brings you to a sign-in page, then I can see that the change in page is a destination. But what if it keeps you on the same page but shows a pop-up with username and password fields? Is that still a destination? Is it then an action?)
* `signout` - "sign out current web site or application" (Similar observation: If it brings you to a new page, that seems destinationy. But if it merely logs you out, keeping you on the same page, that seems more like an action.)

Finally, something that might be worth considering: Is there really value in having actions versus destinations? Reasons I think they might be worth combining into a single property:
1. There seems to be many possibilities for authors to get these things confused.
2. Users who need familiar symbols for terms (e.g. for "help") are probably going to need the same symbol regardless of whether or not "help" is an "action" or a "destination".
3. If I understand things correctly, destination defaults to the ARIA "link" role and "action" defaults to the ARIA "button" role. Why is the type of control relevant to the end user who needs personalization? (Personally, I don't think it is.)

**Comment by becka11y** [comment]
The group really needs to discuss this. All of the issues that are raised above still exist. I tend to agree with Joanie on most of these so perhaps I am not the best person to draft a response...

**Comment by matatk** [comment]
I've been reading through Module 1 and had some questions along these lines too. I agree with @joanmarie's thoughts above, and what I believe is a general implication of your suggestions: that any action whose description begins with "open" feels like a destination.

Regarding combining actions and destinations, that sounds compelling, but as I'm still a newbie in the TF I haven't done enough research to have an opinion on this yet.

I think I have a few related questions to add to @joanmarie's...

Actions:
* Why is there not a `less` action to go with `more`?	
* Could `forward` action be confused with `fast-forward` for media? _Should_ it be?
* We don't seem to have `fast-forward` and `rewind`—or `scrub` as a general alternative—for media, but we do have `play` and `pause`—is this intended?
* As above but with `stop` for media playback (this does do something different to `pause`). (Perhaps `stop` is seen as less common for media playback these days—which risks me diverging off-topic—but I wonder if `stop` as a general action would be of importance anyway.)
* `toc` may not obviously mean `table-of-contents` to everyone, though I appreciate it's shorter. Perhaps we should have `table-of-contents` and `toc` as an alias, though that opens up potentially massive scope-creep—I think `table-of-contents` is clearer.
* The following feel more like destinations:
  - `received`
  - `sent`
  - `settings`
  - `start` (seems generally more like a destination, unless it's meant, in ways like "rewind to the start" or simply "go!")
  - `toc` (which I think should be `table-of-contents` for clarity and consistency with others)
  - `opens-in-page-help` seems more like a destination. Also the name of it is a little inconsistent with others; the tense is more verby or "active" whereas the others are more passive.

Destinations:
* We have `signin` and `signout` but others have hyphens in them, so I would suggest `sign-in` and `sign-out` instead.
* `related` feels like it would be a useful destination, but at the moment it is cast as something that feels more like an action, as @joanmarie mentioned.
* Other stuff as @joanmarie mentioned, though it seems `comment` may have been replaced by `feedback` now?

I have some further, related, questions but will save those for group discussion and/or a different issue thread.

**Comment by matatk** [comment]
I noticed that we do have `media-position` as an action value (which I gather would do what `scrub` does but is a less colloquial term), had missed that one, sorry.

**Comment by matatk** [comment]
Thanks for your input and suggestions, @joanmarie. We have been discussing this extensively lately and have made two significant changes since you opened this issue:

1. We have separated the `action` and `destination` values, so they no longer overlap.
2. We have conducted a review of different approaches involving these attributes (and `purpose`). The [review of approaches is on our wiki](https://github.com/w3c/personalization-semantics/wiki/Review-of-approaches-for-Action,-Destination,-and-Purpose), and it is also linked from various sections in the latest draft (e.g. [§3.1.1 Action Description](https://w3c.github.io/personalization-semantics/content/#description)). The idea behind this was to present some structured information for anyone who may want to provide feedback when we move to the public review/Candidate Recommendation stage.

We're closing this issue as we hope this addresses your concerns, but please let us know if otherwise. We look forward to any feedback you may be able to give on the upcoming candidate spec.
