### ISSUE TITLE
Action table needs to be sorted somehow

### ISSUE THREAD

**Issue by joanmarie** [w3c/personalization-semantics#67]
(Spin-off issue from issue #65, as requested by @clapierre)

The actions table of values does not appear to be grouped in any logical order. Two candidate orders spring to my mind:

* Alphabetical
* Functionality (email, purchases, media controls)

Other orders might make more sense. But given the size of the list (64 items when duplicates have been removed), I think some arrangement will make the list easier to process.

**Comment by ruoxiran** [comment]
there is table of values to be sorted: https://raw.githack.com/w3c/personalization-semantics/rewrite-prototype/content/index.html#values

I will close this issue, thanks.
