### ISSUE TITLE
Is "section-*****" really a field?

### ISSUE THREAD

**Issue by joanmarie** [w3c/personalization-semantics#68]
All of the items in the field table seem like information which the user would provide via an input control. The exception is `section-*****` which is defined as "used to group forms together". The user isn't expected to provide that, correct?

In addition, my understanding of the purpose of the field attribute is that it can:
* Facilitate replacement of existing labels with more easily understood/recognizable words and/or symbols so that the user knows what information is expected
* Work with a personalization-specific form population tool

Assuming my understanding is correct, `section-*****` won't easily be machine parseable because the "*****" (as I understand it) is a wildcard.

With all of the above in mind, is `section-*****` really a field?

**Comment by becka11y** [comment]
Edited document to remove section.*****.

**Comment by becka11y** [comment]
We discussed this in the call and decided that we should discuss further before removing section.  The understanding in the group was that this would be applied to a surrounding element and not directly onto a form element.  It would help to provide more context for the items within the section. For example, home address, shipping address, or billing address.  Another example is using gender surrounding a selection of male or female.  John also brought up that we might need a vocabulary for this and wondered if there are any defined. He could also think of institution examples like a university providing a list of grades or a set of courses within a semester.  We need input from Lisa to understand if this is how she intended section to be used. 

We also discussed removing this for the next editor's draft and addressing in a later draft.

**Comment by thaddeus-cambron** [comment]
The following may provide some initial ground work for thought, although this may not be a 1:1 model for what we would like to accomplish.

https://schema.org/docs/schemas.html

Best,
Thaddeus
________________________________

**Comment by becka11y** [comment]
I agree with JoanMarie that section-***** does not fulfill a field purpose. I am in favor of removing it from this draft. It is not a field type and is essentially mimicking fieldset. If an author does not understand and use fieldsets properly it is unlikely they would use purpose=section-****** correctly.  We should encourage symantic HTML first.

**Comment by clapierre** [comment]
+1
Thanks
EOM
Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
Twitter: @CLaPierreA11Y
Skype: charles_lapierre


On Mar 30, 2020, at 6:53 AM, Becky Gibson <notifications@github.com<mailto:notifications@github.com>> wrote:



I agree with JoanMarie that section-***** does not fulfill a field purpose. I am in favor of removing it from this draft. It is not a field type and is essentially mimicking fieldset. If an author does not understand and use fieldsets properly it is unlikely they would use purpose=section-****** correctly. We should encourage symantic HTML first.

**Comment by becka11y** [comment]
So, on a further investigation - section-**** is part of the available HTML5 autofill values. See example 74 on this page:  https://www.w3.org/TR/html52/sec-forms.html#sec-autofill. 

 It is how you can further distinguish values - "section-item1 shipping postal-code", "section-item2 shipping postal-code", "section-item2 billing postal-code", etc. . The list referenced in WCAG 2.1 (https://www.w3.org/TR/WCAG21/#input-purposes) includes only discrete values.  Since we will be referring to the WCAG values, I believe it makes even more sense to remove section-****.

**Comment by becka11y** [comment]
TF discussion on March 8, 2020 and agreed to remove section-**** based on above comment from March 30, 2020.

**Comment by ruoxiran** [comment]
Removed in PR #174, we could close this issue, thanks
