### ISSUE TITLE
Link to module "Adaptable Help and support" goes to "document not found"

### ISSUE THREAD

**Issue by ghost** [w3c/personalization-semantics#69]
In the Personalization Semantics Explainer 1.0 document, "Adaptable Help and support" link should resolve to the appropriate document.

In the link text "Adaptable Help and support", "support" should be uppercase - "Support".

**Comment by becka11y** [comment]
The link goes to https://w3c.github.io/personalization-semantics/help/index.html (which is labeled as the June 20 draft).  Is this correct?

**Comment by clapierre** [comment]
Ok I believe I see the issue with the [Working Draft 16 March 2018 version](https://www.w3.org/TR/personalization-semantics-1.0/#modules) not the current [Editors Draft version](https://w3c.github.io/personalization-semantics/)

This is fine as we haven't published our first Public Working Draft of this module.
