### ISSUE TITLE
Explainer for adaptable content: use cases, problem statement, alternatives considered and expected applications

### ISSUE THREAD

**Issue by samuelgoto** [w3c/personalization-semantics#72]
Is there a (good, solid, crisp, concrete) doc I could be reading about the expected applications of the [Adaptable Content Module](https://w3c.github.io/personalization-semantics/content/index.html)? I'm looking for a crispier definition of the problem that you are addressing (i.e. what **specifically** are you trying to address from a user experience perspective) before you introduce any specific solution (e.g. field names, attribute names, etc).

> This can include:
> Symbols and graphics that they are familiar with
> Tooltips
> Language the use can understand
> Keyboard short cuts

There are a paragraph or two in the [spec](https://w3c.github.io/personalization-semantics/content/index.html#use-cases) with a lot of vague applications (e.g. "This can include" -- but will it really?) in [this](https://w3c.github.io/personalization-semantics/content/index.html#use_case_adding_context) section, but I'm having a hard time taking these applications seriously (e.g. if you were really trying to solve each of these individual problems, would we really chose to use the solution specified here?).

I'm specifically interested in understanding what kinds of problems you are trying to solve with properties like ```action```, ```destination``` and ```field``` as well as the [possible values](https://www.w3.org/TR/2018/WD-personalization-semantics-content-1.0-20180316/#values) it takes (e.g. compose, delete, confirm, etc).

For example, take a single instantiation of these values and help me understand how this works. E.g. if action="compose", how would you expect here the User Agent would help?

Do we already have a solid doc (i.e. an in-depth/full understanding of the user pain and how we think user agents can help) going over the problem that we are trying to solve from a user experience perspective? If so, pointers? If not, should one be created?

Things I'd want to find in a solid explainer:

- a crisp definition of the problem statement
  - canonical examples
- related technologies
- prior art
  - does a similar problem appear in a different platform (e.g. windows? mac? android? ios?)
- alternatives being considered
- design of incentives: are incentives well-aligned between involved parties?

PS FWIW, I'm having a better time understanding how the [Adaptable Help and Support](https://w3c.github.io/personalization-semantics/help/index.html) module can effectively help a user.

**Comment by AreaOfAKite** [comment]
Hi Sam. The Personalization TF originated in the COGA TF. While it may not have all the answers you are looking for and we may be need to repurpose this information more specifically to suit the needs of the the Adaptable Content Module, it may helpful to take a look at the [Cognitive Accessibility User Research document](https://w3c.github.io/coga/user-research/).

**Comment by samuelgoto** [comment]
@AreaOfAKite the doc that you pointed is really really good. A lot of solid data points there.

I specifically like the section on [user stories](https://w3c.github.io/coga/user-research/#scenarios-and-user-stories) and the overview of [existing technologies](https://w3c.github.io/coga/user-research/#specific-technologies).

I'm having a hard time, though, (a) connecting the dots here between this extensive doc and the specific problems you are trying to solve with the proposed modules (e.g. which **specific** user stories are being addressed in each part of the modules) and (b) a throughout analysis of alternatives considered (e.g. why this **specific** solution is better than any other direction we could take). 

For example, for [this example](https://w3c.github.io/personalization-semantics/content/index.html#action-example) of markup proposed in the module:

```html
<button aui-action="undo" >Revert</button>
```

Can you walk me through, specifically for this example:

- how does this connect with a specific user story identified in the user research (or elsewhere)?
- what is the user agent supposed to do to aid the user?
- what alternatives were considered to satisfy that user story and why is that that specific proposal is favorable (e.g. from a design of incentives perspective, ergonomics, extensibility, layering, etc)?

**Comment by AreaOfAKite** [comment]
Thank you @samuelgoto. I probably should have provided additional context around the Cognitive Accessibility User Research document. This document was the foundation for work done in the COGA TF vs. the Personalization TF. I believe what I am hearing is that your recommendation would be that we deliver a similar document to support our work on Personalization and I personally agree with you on this. There may be some information from the Cognitive Accessibility User Research document that we can leverage to start this effort. @lseeman and @clapierre do you see value in creating a similar document for the Personalization TF and is this something we could get started on now or very soon? 

@samuelgoto, with that said, there is no current, direct correlation between `<button aui-action="undo" >Revert</button>` and the user stories in the Cognitive Accessibility User Research document. The Personalization TF was born out of COGA, however, I believe the vision of Personalization is to include cognitive disability but also to extend beyond cognitive disability. Is this additional context helpful?

**Comment by samuelgoto** [comment]
> I believe what I am hearing is that your recommendation would be that we deliver a similar document to support our work on Personalization and I personally agree with you on this.

Yep, that summarizes well. That doc is extremely well written and comprehensive, but seems broader (and hence shallower) than the work being done.

> Is this additional context helpful?

Yep, but also seems also like additional supportive evidence that you want a doc that is more specific than the one you linked above.

> what alternatives were considered to satisfy that user story and why is that that specific proposal is favorable (e.g. from a design of incentives perspective, ergonomics, extensibility, layering, etc)?

I read quickly the doc you sent me (it is long), but I didn't find enough content around alternatives considered (it was  user research doc, so probably not the best place to go over there). Is that compiled somewhere, and if not, should we?

**Comment by clapierre** [comment]
Hi Sam, See below

For example, for this example<https://w3c.github.io/personalization-semantics/content/index.html#action-example> of markup proposed in the module:

<button aui-action="undo" >Revert</button>

Can you walk me through, specifically for this example:

  *   what is the user agent supposed to do to aid the user?


Hi Sam, for this I could see a use for a person with a cognitive disability where they recognize a certain picture as being “Undo”  but web developers use what ever text they wish to represent this like “revet”, “go back”, “erase”, “undo”, and this particular user’s preference would be to have a icon [Image result for undo icons]
show up instead of what the author had, and possibly even change the text of the button to say “Undo” instead of “Revert” as they don’t know what “Revert” means but they understand “Undo”  So a user agent could make this changes before the page is rendered to accommodate his personal preferences.

At least this is my understanding of how this might work.  If others have some thoughts I would love to hear it.
Thanks
Charles.

**Comment by samuelgoto** [comment]
> So a user agent could make this changes before the page is rendered to accommodate his personal preferences

What makes us believe that this is the responsibility of the User Agent as opposed to the content author? That is, what makes us believe that the content author should declaratively state what are the semantics of the affordance and let the user agent figure out what to do?

Is there anything that this declarative affordance (i.e. the aui-action property) unlocks that **couldn't** be done before by the developer with custom CSS/HTML/JS (e.g. something that crosses security boundaries or has access to lower level APIs)?  

What is it that we are buying moving this to the user agent layer? Consistency? Ergonomics? Implementation cost? Composition? Lower level access (e.g. ARIA gives declarative access to screen reader's API)?

What other alternatives have we explored to satisfy this use case? Why shouldn't we expose a javascript API like `document.preferences.textToPictures // returns true if the user has a preference for text over pictures` and let the developer figure out what to do with that setting (isomorphic question to "why should this be the responsibility of the user agent")?

Sorry if this is a silly question, but I couldn't find an immediate answer reading your docs.

**Comment by AreaOfAKite** [comment]
I think these are really good points regarding implementation. I believe we were headed down a good path of conversation regarding use cases and potentially having some actionable items to provide additional context to the personalization semantics. Do you think there is any value to moving the conversations regarding implementation to another issue so we don't lose focus on activities related to supporting use cases and problem statements?

**Comment by clapierre** [comment]
Creating a new issue on implementation and copying over these last few comments would be my vote.  Anyone object?
Thanks
EOM

Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
E-mail: charlesl@benetech.org<mailto:charlesl@benetech.org>
Twitter: @CLaPierreA11Y
Skype: charles_lapierre
Phone: 650-600-3301



On May 14, 2018, at 5:40 PM, Thaddeus Cambron <notifications@github.com<mailto:notifications@github.com>> wrote:


I think these are really good points regarding implementation. I believe we were headed down a good path of conversation regarding use cases and potentially having some actionable items to provide additional context to the personalization semantics. Do you think there is any value to moving the conversations regarding implementation to another issue so we don't lose focus on activities related to supporting use cases and problem statements?

**Comment by AreaOfAKite** [comment]
+1 - I can take some ownership of the use cases/problem statement or at least discuss with @lseeman, as she initiated the COGA documentation. I also used this document as a participant in the COGA TF

**Comment by samuelgoto** [comment]
Sgtm. I'll kick off another bug.

(apologies for the brevity, sent from phone)

**Comment by lseeman** [comment]
did we look at the use cases at  https://rawgit.com/w3c/personalization-semantics/master/semantics.html#semanticProperties

**Comment by lseeman** [comment]
also https://www.w3.org/TR/coga-gap-analysis/ 
of particular interest is 
1, the roadmap section https://www.w3.org/TR/coga-gap-analysis/#tables-of-user-needs which describes how personalization can be used in a matrix of solutions for user needs. 
2 . https://www.w3.org/TR/coga-gap-analysis/#personalization-and-user-preferences which describes the issues in personalization.
3.  this is based on an issue paper at https://w3c.github.io/coga/issue-papers/personalization-preferences.html

**Comment by johnfoliot** [comment]
There have been substantial edits to the document. Closed as resolved over time.
