### ISSUE TITLE
Prior art, comparison and trade-offs of taxonomy used in Adaptable Content Module

### ISSUE THREAD

**Issue by samuelgoto** [w3c/personalization-semantics#74]
The adaptable content module lists an enumeration of action-like tags (e.g. undo, remove, etc).

Is there a doc/section going over where we looked at before compiling that list?

FWIW, here are a few things that I'd expect to see in a background research section somewhere in your explainer:

- academically: framenet, verbnet, wordnet
- standards track: [activity streams](https://www.w3.org/TR/activitystreams-core/) and [schema.org actions](http://blog.sgo.to/2014/02/a-taxonomy-for-verbs.html)
- industry applications: [opengraph actions](https://developers.facebook.com/docs/sharing/opengraph/using-actions), [gmail actions](https://developers.google.com/gmail/markup/actions/actions-overview), search actions

These are all more action-oriented and don't cover your other modules (e.g. easylang, numfree, etc). There were also designed for a different application (activity streams for social applications and schema.org for search/conversational assistants, e.g. alexa/siri/home) but seemed like somewhat related technologies.

**Comment by thaddeus-cambron** [comment]
Is the current research listed in the initial issue allocated to someone?

**Comment by clapierre** [comment]
Hello @samuelgoto thank you for this feedback, we think this is no longer relevant as our module has evolved over the past two years.  Our module and explainer here has gone through a FPWD and has gone though a wider review as well.  
Please do take a look at our latest 
[Explainer](https://www.w3.org/TR/personalization-semantics-1.0/)
and
[Semantic Content Module](https://www.w3.org/TR/personalization-semantics-content-1.0/)

Please let us know if you have any additional concerns.
