### ISSUE TITLE
Overloading the term `semantics`?

### ISSUE THREAD

**Issue by LJWatson** [w3c/personalization-semantics#78]
The discussion in #73 surfaces a question that I've been thinking about lately...

Are we overloading the term `semantics`? We've spent many years getting authors used to the idea that semantics relate to the purpose (role) of an element, or its other characteristics (name, state, etc.).

Now we propose to extend the definition of `semantics` to encompass an elements visual representation (under certain circumstances). I wonder whether this will cause confusion, and consequently make things harder for authors to understand and adopt?

**Comment by lseeman** [comment]
Hi Leonie!

We agree that  authors are (hopefully) used to the idea that semantics
relate to the purpose (role) of an element, or its other characteristics
(name, state, etc.). 

We think our specification is part of that. For example, the purpose of
this field is to get your email address, or the purpose of a link is to
take you to the contact us Page.

  It makes the purpose of the element machine readable. 

The definition of semantics is the branch of linguistics and logic concerned with meaning 
 and more specifically,  conceptual semantics, which studies the cognitive structure of meaning.
For symbols, it makes the meaning of the symbol  machine readable. 

Hope that helps , and thanks for the review
