### ISSUE TITLE
To be inter-operable, our definitions need to be normative

### ISSUE THREAD

**Issue by johnfoliot** [w3c/personalization-semantics#83]
To meet the needs of i18n and machine inter-operability, our taxonomy definition will need to be normative. 

Additionally, whatever definition we agree to must be testable and scalable if we hope to make these measurable requirements at some point (as opposed to author best practices). For example, what is a "short sentence"? Less than 5 words? Less than 10 words? Content authors striving to meet these goals will need to have a definition of what success looks like, and for compliance requirements the results need to be testable and repeatable.

**Comment by lseeman** [comment]
@johnfoliot  Can you review and check the value values in the current draft are good enough yet (for module 1) ?

**Comment by lwolberg** [comment]
John feels that with the addition of the COGA glossary and the multiple editorial reviews since then, this is resolved.

**Comment by johnfoliot** [comment]
Resolved, and closed with group consensus
