### ISSUE TITLE
Web Annotation as potential implementation

### ISSUE THREAD

**Issue by ghost** [w3c/personalization-semantics#84]
Add Web Annotation as an implementation.

https://www.w3.org/TR/annotation-model/

**Comment by thaddeus-cambron** [comment]
This issue was opened as a task to add annotations as an additional implementing technology vs research on the topic. If research is needed please let me know.

**Comment by thaddeus-cambron** [comment]
Web Annotations was added to the comparison chart. This issue can be closed unless there is additional research to be done on the  topic.
