### ISSUE TITLE
Improve Introduction and Use Cases

### ISSUE THREAD

**Issue by ghost** [w3c/personalization-semantics#85]
Initial draft to improve Introduction and use cases in explainer module. Will create new branch for proposed revisions.

**Comment by thaddeus-cambron** [comment]
Is this still a valid assignment for me. I believe that Becky has a pull request in for this, however, I could be mistaken.

**Comment by clapierre** [comment]
This is still in need of some work as Becky's editorial changes in #86 addressed #1, #44, and #45 all of which have been now closed.
